# Generated by Django 2.2 on 2020-07-12 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('corporate_headoffice', 'Corporate Headoffice'), ('retailer_branch', 'Retailer Branch'), ('factory', 'Factory'), ('warehouse', 'Warehouse')], db_index=True, default='corporate_headoffice', max_length=30, verbose_name='Location')),
                ('incident_description', models.TextField(max_length=200, verbose_name='Incident Description')),
                ('date_time_of_incident', models.DateTimeField(blank=True, verbose_name='Date and Time of Incident')),
                ('incident_location', models.TextField(blank=True, max_length=200, verbose_name='Incident Location')),
                ('initial_severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('critical', 'Critical')], default='moderate', max_length=30)),
                ('suspected_cause', models.TextField(blank=True, max_length=200, verbose_name='Suspected Cause')),
                ('immediate_action_taken', models.TextField(blank=True, max_length=200, verbose_name='Immediate Action Taken')),
                ('sub_incident_types', models.CharField(blank=True, choices=[('environmental_incident', 'Environmental Incident'), ('injury_illness', 'Injury/Illness'), ('property_damage', 'Property Damage'), ('vehicle', 'Vehicle')], max_length=30)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
